services:

  localdb:
    image: container-registry.oracle.com/database/free:latest
#    image: container-registry.oracle.com/database/enterprise:19.3.0.0
    ports:
      - 1521:1521
    volumes:
      - ./localdb/scripts:/opt/oracle/scripts/startup
      - local_db_volume:/opt/oracle/oradata
    environment:
      - ORACLE_PWD=localdbadmin
      - ORACLE_CHARACTERSET=AL32UTF8
      - LOCAL_DB_USER=TEST_USER
      - LOCAL_DB_USER_PWD=local1Psw0rd
    networks:
      - local_network
volumes:
  local_db_volume:

networks:
  local_network:
    external: true
