WHENEVER SQLERROR EXIT SQL.SQLCODE;
ALTER SESSION SET CONTAINER = ENTERPRISEPDB1;
ALTER SESSION SET CURRENT_SCHEMA = TEST_USER;

-- Authors Table
CREATE TABLE authors (
    author_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name VARCHAR2(100) NOT NULL,
    last_name VARCHAR2(100) NOT NULL,
    birth_date DATE
);

-- Genres Table
CREATE TABLE genres (
    genre_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR2(100) NOT NULL UNIQUE
);

-- Books Table
CREATE TABLE books (
    book_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR2(255) NOT NULL,
    isbn VARCHAR2(20) UNIQUE,
    publication_date DATE,
    author_id NUMBER,
    genre_id NUMBER,
    CONSTRAINT fk_books_author FOREIGN KEY (author_id) REFERENCES authors(author_id),
    CONSTRAINT fk_books_genre FOREIGN KEY (genre_id) REFERENCES genres(genre_id)
);

COMMIT;

-- Exit SQL*Plus (optional)
-- EXIT;
